import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { validateEmail } from './validation';

/**
 * Property 3: Email format validation
 * **Validates: Requirements 5.4**
 *
 * For any string that matches a valid email pattern (local@domain.tld),
 * validateEmail should return true. For any string that does not contain
 * exactly one @ separating a non-empty local part and a domain with at
 * least one dot, validateEmail should return false.
 */
describe('Property 3: Email format validation', () => {
  /**
   * **Validates: Requirements 5.4**
   *
   * Valid emails generated by fc.emailAddress() that conform to our
   * validation rules (local@domain.tld with at least one dot in domain
   * and all domain parts non-empty) must return true.
   */
  it('returns true for valid emails matching local@domain.tld format', () => {
    // Filter fc.emailAddress() to only include emails that match our
    // stricter validation rules: exactly one @, non-empty local part,
    // domain with at least one dot, and all domain parts non-empty.
    const validEmailArb = fc.emailAddress().filter((email) => {
      const atParts = email.split('@');
      if (atParts.length !== 2) return false;
      const [localPart, domain] = atParts;
      if (!localPart) return false;
      if (!domain || !domain.includes('.')) return false;
      const domainParts = domain.split('.');
      return domainParts.every((part) => part.length > 0);
    });

    fc.assert(
      fc.property(validEmailArb, (email) => {
        expect(validateEmail(email)).toBe(true);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * **Validates: Requirements 5.4**
   *
   * Random strings that do not have a valid email structure must return false.
   * We filter fc.string() to exclude strings that happen to be valid emails.
   */
  it('returns false for random invalid strings without valid email structure', () => {
    const invalidStringArb = fc.string().filter((s) => {
      const trimmed = s.trim();
      // Exclude empty strings (trivially invalid, not interesting)
      if (trimmed.length === 0) return true;
      // Keep strings that do NOT match valid email structure
      const atParts = trimmed.split('@');
      if (atParts.length !== 2) return true; // no @ or multiple @
      const [localPart, domain] = atParts;
      if (!localPart) return true; // empty local part
      if (!domain || !domain.includes('.')) return true; // no dot in domain
      const domainParts = domain.split('.');
      if (domainParts.some((part) => !part)) return true; // empty domain part
      // This string looks like a valid email — exclude it
      return false;
    });

    fc.assert(
      fc.property(invalidStringArb, (str) => {
        expect(validateEmail(str)).toBe(false);
      }),
      { numRuns: 100 }
    );
  });
});
